project:
  type: book
  output-dir: docs

book:
  title: "Investigaciones en gestión del riesgo de desastres para Colombia"
  chapters:
    - index.qmd
    - capitulos/00_legal.qmd
    - capitulos/00_intro_previa.qmd
    - capitulos/03_prologo.qmd
    - capitulos/05_seccion_abstract.qmd
    - capitulos/05_seccion_agradecimientos.qmd
    - capitulos/05_seccion_anexo_1_espectros_de_diseno_propuestos_p.qmd
    - capitulos/05_seccion_aplicaciones_en_la_ciudad_santiago_de_ca.qmd
    - capitulos/05_seccion_bibliografia.qmd
    - capitulos/05_seccion_breve_resena_de_los_desastres_en_colombi.qmd
    - capitulos/05_seccion_caso_de_aplicacion.qmd
    - capitulos/05_seccion_caso_de_estudio_sequia_en_colombia.qmd
    - capitulos/05_seccion_coeficientes_optimos.qmd
    - capitulos/05_seccion_conclusiones.qmd
    - capitulos/05_seccion_conflicto_de_interes.qmd
    - capitulos/05_seccion_conflicto_de_intereses.qmd
    - capitulos/05_seccion_discusion.qmd
    - capitulos/05_seccion_discusion_y_conclusiones.qmd
    - capitulos/05_seccion_espectros_de_diseno.qmd
    - capitulos/05_seccion_espectros_propuestos_y_comparacion_con_l.qmd
    - capitulos/05_seccion_estudios_tecnicos_de_validacion_y_priori.qmd
    - capitulos/05_seccion_evaluacion_del_riesgo_por_sequia_en_el_s.qmd
    - capitulos/05_seccion_evaluacion_probabilista_de_la_amenaza_po.qmd
    - capitulos/05_seccion_evaluacion_probabilista_del_riesgo_por_s.qmd
    - capitulos/05_seccion_exposicion_agricola.qmd
    - capitulos/05_seccion_geodesia_de_imagenes_para_el_estudio_de_.qmd
    - capitulos/05_seccion_geodesia_espacial_gps_y_el_estudio_de_la.qmd
    - capitulos/05_seccion_gestion_del_riesgo_en_cali_y_su_relacion.qmd
    - capitulos/05_seccion_identificacion_de_autor.qmd
    - capitulos/05_seccion_identificacion_de_zonas_criticas_departa.qmd
    - capitulos/05_seccion_identificacion_del_autor.qmd
    - capitulos/05_seccion_introduccion.qmd
    - capitulos/05_seccion_keywords.qmd
    - capitulos/05_seccion_la_comunicacion_del_riesgo_algunas_refle.qmd
    - capitulos/05_seccion_la_fuerza_de_las_experiencias.qmd
    - capitulos/05_seccion_lineamientos_para_la_gestion_del_riesgo_.qmd
    - capitulos/05_seccion_los_estudios_historicos_en_la_gestion_de.qmd
    - capitulos/05_seccion_materiales_y_metodos.qmd
    - capitulos/05_seccion_metodologia.qmd
    - capitulos/05_seccion_movimientos_sismicos_de_diseno.qmd
    - capitulos/05_seccion_obras_costeras_y_su_efecto.qmd
    - capitulos/05_seccion_palabras_clave.qmd
    - capitulos/05_seccion_recomendaciones_generales.qmd
    - capitulos/05_seccion_representacion_de_la_vulnerabilidad_para.qmd
    - capitulos/05_seccion_resultados.qmd
    - capitulos/05_seccion_resultados_y_discusion.qmd
    - capitulos/05_seccion_resumen.qmd
    - capitulos/05_seccion_salud_publica_y_epidemiologia_alrededor_.qmd
    - capitulos/05_seccion_tipologias_predominantes_en_el_sector.qmd
    - capitulos/05_seccion_un_nuevo_enfoque.qmd
    - capitulos/05_seccion_validacion_de_resultados.qmd
    - capitulos/05_seccion_zona_de_estudio.qmd
    - capitulos/99_indice.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: false
    page-navigation: true
